# Site settings
title: PersonalStarterKit
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
exclude: ["node_modules","gulpfile.js","package.json"]
