# Site settings
title: ichzwei.null - Web, Design und Entwicklung
description: > # this means to ignore newlines until "baseurl:"
  Portfolio von Sascha Mersch, Webdesigner in Berlin
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
exclude: ["node_modules","gulpfile.js","package.json"]
