menu:
- {title: Home, url: 'home'}
- {title: Projekte, url: 'projects'}
- {title: Über, url: 'about'}
- {title: Kontakt, url: 'contact'}

projects:
- {title: Personal Excellence, image: personal-excellence.jpg, folder: 'project-1', header: 'project-1', text: 'Umfangreiches responsives Webdesign für eine Berliner Personalberatung mit integrierter Stellenbörse.'}
- {title: Louis Busman, image: louis-busman.jpg, folder: 'project-2', header: 'project-2', text: 'Leichte Texturen schaffen einen dezenten Rahmen für die Werke des Künstlers Louis Busman.'}
- {title: Kleine Nachtrevue, image: kleine-nachtrevue.jpg, folder: 'project-3', header: 'project-3', text: 'Ein erfolgreiches frisches Branding und responsives Webdesign für das Berliner Burlesque-Theater.'}

clients:
- {name: Uwe Schmidt, company: Werkraum, image: uwe-schmidt.png, text: 'Sascha Mersch hat mich von der ersten Idee bis zum Launch komplett begleitet und zu einer wunderbaren Website verholfen, die bei meinen Kunden ohne Ausnahme großen Eindruck hinterlassen hat.'}
- {name: Esther Kimmel, company: Kimmelcoaching, image: esther-kimmel.png, text: 'Was ich selbst gar nicht so klar ausdrücken konnte, haben Sie offenbar intuitiv erfasst und umgesetzt: mit einem sehr guten Gespür dafür, was zu mir als Person und gleichzeitig zu meiner Branche passt.'}
- {name: Tamara Kunze, company: Personal Excellence, image: tamara-kunze.png, text: 'Schon von dem ersten Entwurf war ich gleich begeistert. Auch war ich beeindruckt von der Schnelligkeit der Bearbeitung – sowohl bei der Erstellung der Homepage als auch bei der weiteren Zusammenarbeit.'}

company: ichzwei.null
name: Sascha Mersch
street: Motzstraße 61
city: 10777 Berlin
phone: +49 (0)30 27574647
email: info@ichzweinull.com
taxid: DE279332980
github: https://github.com/rschach/ichzweinull

title: ichzwei.null - Webdesign &amp; Entwicklung
description: Ich gestalte und entwickle erfolgreiche responsive Websites für Unternehmen, Selbstständige, Locations und Künstler.
