menu:
- {title: Home, url: 'home'}
- {title: Projekte, url: 'projects'}
- {title: Über, url: 'about'}
- {title: Kontakt, url: 'contact'}

projects:
- {title: Personal Excellence, image: personal-excellence.jpg, folder: 'project-1', header: 'header-1', text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.'}
- {title: Werkraum, image: werkraum.jpg, folder: 'project-2', header: 'header-2', text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.'}
- {title: Kleine Nachtrevue, image: kleine-nachtrevue.jpg, folder: 'project-3', header: 'header-3', text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.'}

clients:
- {name: Uwe Schmidt, company: Werkraum, image: uwe-schmidt.png, text: 'Sascha Mersch hat mich von der ersten Idee bis zum Launch komplett begleitet und zu einer wunderbaren Website verholfen, die bei meinen Kunden ohne Ausnahme großen Eindruck hinterlassen hat.'}
- {name: Esther Kimmel, company: Kimmelcoaching, image: esther-kimmel.png, text: 'Was ich selbst gar nicht so klar ausdrücken konnte, haben Sie offenbar intuitiv erfasst und umgesetzt: mit einem sehr guten Gespür dafür, was zu mir als Person und gleichzeitig zu meiner Branche passt.'}
- {name: Tamara Kunze, company: Personal Excellence, image: tamara-kunze.png, text: 'Sie zeigten ein tolles Gespür für das, was unser Unternehmen ausmacht und wie man dies gut darstellen kann. Schon von dem ersten Entwurf war ich gleich begeistert.'}
